namespace NguyenTienDat_10122119
{
    partial class frmForgetPassword
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmForgetPassword));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnSend = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtSecureCode = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnChangePassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnSignIn = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSignUp = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel5);
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Controls.Add(this.bunifuImageButton1);
            this.bunifuPanel1.Location = new System.Drawing.Point(1, 2);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(396, 31);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 12.75F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.Location = new System.Drawing.Point(39, 3);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(131, 21);
            this.bunifuLabel5.TabIndex = 8;
            this.bunifuLabel5.Text = "Forget Password";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::NguyenTienDat_10122119.Properties.Resources.icons8_remote_desktop_ios_16_filled_701;
            this.pictureBox1.Location = new System.Drawing.Point(3, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(30, 30);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = global::NguyenTienDat_10122119.Properties.Resources.icons8_exit_ios_16_70;
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(24, 24);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(25, 25);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(368, 3);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = false;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(25, 25);
            this.bunifuImageButton1.TabIndex = 0;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Black;
            this.bunifuLabel1.Location = new System.Drawing.Point(102, 66);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(156, 25);
            this.bunifuLabel1.TabIndex = 8;
            this.bunifuLabel1.Text = "Reset password";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.BackColor = System.Drawing.Color.White;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.Silver;
            this.bunifuLabel2.Location = new System.Drawing.Point(31, 109);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(310, 16);
            this.bunifuLabel2.TabIndex = 9;
            this.bunifuLabel2.Text = "Change password after verifying email address";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnSend
            // 
            this.btnSend.AllowAnimations = true;
            this.btnSend.AllowMouseEffects = true;
            this.btnSend.AllowToggling = false;
            this.btnSend.AnimationSpeed = 200;
            this.btnSend.AutoGenerateColors = false;
            this.btnSend.AutoRoundBorders = false;
            this.btnSend.AutoSizeLeftIcon = true;
            this.btnSend.AutoSizeRightIcon = true;
            this.btnSend.BackColor = System.Drawing.Color.Transparent;
            this.btnSend.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSend.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSend.BackgroundImage")));
            this.btnSend.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSend.ButtonText = "Send";
            this.btnSend.ButtonTextMarginLeft = 0;
            this.btnSend.ColorContrastOnClick = 45;
            this.btnSend.ColorContrastOnHover = 45;
            this.btnSend.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSend.CustomizableEdges = borderEdges5;
            this.btnSend.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSend.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSend.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSend.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSend.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSend.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSend.ForeColor = System.Drawing.Color.White;
            this.btnSend.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSend.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSend.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSend.IconMarginLeft = 11;
            this.btnSend.IconPadding = 10;
            this.btnSend.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSend.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSend.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSend.IconSize = 25;
            this.btnSend.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSend.IdleBorderRadius = 15;
            this.btnSend.IdleBorderThickness = 1;
            this.btnSend.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSend.IdleIconLeftImage = null;
            this.btnSend.IdleIconRightImage = null;
            this.btnSend.IndicateFocus = false;
            this.btnSend.Location = new System.Drawing.Point(228, 194);
            this.btnSend.Name = "btnSend";
            this.btnSend.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSend.OnDisabledState.BorderRadius = 15;
            this.btnSend.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSend.OnDisabledState.BorderThickness = 1;
            this.btnSend.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSend.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSend.OnDisabledState.IconLeftImage = null;
            this.btnSend.OnDisabledState.IconRightImage = null;
            this.btnSend.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSend.onHoverState.BorderRadius = 15;
            this.btnSend.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSend.onHoverState.BorderThickness = 1;
            this.btnSend.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSend.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSend.onHoverState.IconLeftImage = null;
            this.btnSend.onHoverState.IconRightImage = null;
            this.btnSend.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSend.OnIdleState.BorderRadius = 15;
            this.btnSend.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSend.OnIdleState.BorderThickness = 1;
            this.btnSend.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSend.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSend.OnIdleState.IconLeftImage = null;
            this.btnSend.OnIdleState.IconRightImage = null;
            this.btnSend.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSend.OnPressedState.BorderRadius = 15;
            this.btnSend.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSend.OnPressedState.BorderThickness = 1;
            this.btnSend.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSend.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSend.OnPressedState.IconLeftImage = null;
            this.btnSend.OnPressedState.IconRightImage = null;
            this.btnSend.Size = new System.Drawing.Size(110, 35);
            this.btnSend.TabIndex = 14;
            this.btnSend.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSend.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSend.TextMarginLeft = 0;
            this.btnSend.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSend.UseDefaultRadiusAndThickness = true;
            this.btnSend.Click += new System.EventHandler(this.btnSend_Click);
            // 
            // txtSecureCode
            // 
            this.txtSecureCode.AcceptsReturn = false;
            this.txtSecureCode.AcceptsTab = false;
            this.txtSecureCode.AnimationSpeed = 200;
            this.txtSecureCode.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSecureCode.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSecureCode.BackColor = System.Drawing.Color.Transparent;
            this.txtSecureCode.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSecureCode.BackgroundImage")));
            this.txtSecureCode.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSecureCode.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSecureCode.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSecureCode.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSecureCode.BorderRadius = 10;
            this.txtSecureCode.BorderThickness = 1;
            this.txtSecureCode.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSecureCode.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSecureCode.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSecureCode.DefaultText = "";
            this.txtSecureCode.FillColor = System.Drawing.Color.White;
            this.txtSecureCode.ForeColor = System.Drawing.Color.Black;
            this.txtSecureCode.HideSelection = true;
            this.txtSecureCode.IconLeft = global::NguyenTienDat_10122119.Properties.Resources.icons8_verification_ios_16_filled_96;
            this.txtSecureCode.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSecureCode.IconPadding = 0;
            this.txtSecureCode.IconRight = null;
            this.txtSecureCode.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSecureCode.Lines = new string[0];
            this.txtSecureCode.Location = new System.Drawing.Point(47, 194);
            this.txtSecureCode.MaxLength = 32767;
            this.txtSecureCode.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSecureCode.Modified = false;
            this.txtSecureCode.Multiline = false;
            this.txtSecureCode.Name = "txtSecureCode";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSecureCode.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSecureCode.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSecureCode.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSecureCode.OnIdleState = stateProperties16;
            this.txtSecureCode.Padding = new System.Windows.Forms.Padding(3);
            this.txtSecureCode.PasswordChar = '\0';
            this.txtSecureCode.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSecureCode.PlaceholderText = "Verification code";
            this.txtSecureCode.ReadOnly = false;
            this.txtSecureCode.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSecureCode.SelectedText = "";
            this.txtSecureCode.SelectionLength = 0;
            this.txtSecureCode.SelectionStart = 0;
            this.txtSecureCode.ShortcutsEnabled = true;
            this.txtSecureCode.Size = new System.Drawing.Size(175, 33);
            this.txtSecureCode.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSecureCode.TabIndex = 13;
            this.txtSecureCode.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSecureCode.TextMarginBottom = 0;
            this.txtSecureCode.TextMarginLeft = 8;
            this.txtSecureCode.TextMarginTop = 0;
            this.txtSecureCode.TextPlaceholder = "Verification code";
            this.txtSecureCode.UseSystemPasswordChar = false;
            this.txtSecureCode.WordWrap = true;
            // 
            // txtPassword
            // 
            this.txtPassword.AcceptsReturn = false;
            this.txtPassword.AcceptsTab = false;
            this.txtPassword.AnimationSpeed = 200;
            this.txtPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPassword.BackColor = System.Drawing.Color.Transparent;
            this.txtPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPassword.BackgroundImage")));
            this.txtPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtPassword.BorderRadius = 10;
            this.txtPassword.BorderThickness = 1;
            this.txtPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPassword.DefaultText = "";
            this.txtPassword.FillColor = System.Drawing.Color.White;
            this.txtPassword.ForeColor = System.Drawing.Color.Black;
            this.txtPassword.HideSelection = true;
            this.txtPassword.IconLeft = global::NguyenTienDat_10122119.Properties.Resources.icons8_locked_ios_16_70;
            this.txtPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.IconPadding = 0;
            this.txtPassword.IconRight = null;
            this.txtPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPassword.Lines = new string[0];
            this.txtPassword.Location = new System.Drawing.Point(47, 250);
            this.txtPassword.MaxLength = 32767;
            this.txtPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPassword.Modified = false;
            this.txtPassword.Multiline = false;
            this.txtPassword.Name = "txtPassword";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPassword.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPassword.OnIdleState = stateProperties20;
            this.txtPassword.Padding = new System.Windows.Forms.Padding(3);
            this.txtPassword.PasswordChar = '*';
            this.txtPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtPassword.PlaceholderText = "New password";
            this.txtPassword.ReadOnly = false;
            this.txtPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPassword.SelectedText = "";
            this.txtPassword.SelectionLength = 0;
            this.txtPassword.SelectionStart = 0;
            this.txtPassword.ShortcutsEnabled = true;
            this.txtPassword.Size = new System.Drawing.Size(291, 37);
            this.txtPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtPassword.TabIndex = 12;
            this.txtPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPassword.TextMarginBottom = 0;
            this.txtPassword.TextMarginLeft = 8;
            this.txtPassword.TextMarginTop = 0;
            this.txtPassword.TextPlaceholder = "New password";
            this.txtPassword.UseSystemPasswordChar = false;
            this.txtPassword.WordWrap = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.BackColor = System.Drawing.Color.Transparent;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmail.BorderRadius = 10;
            this.txtEmail.BorderThickness = 1;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Century Gothic", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.White;
            this.txtEmail.ForeColor = System.Drawing.Color.Black;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = global::NguyenTienDat_10122119.Properties.Resources.icons8_email_24;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 0;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(47, 145);
            this.txtEmail.MaxLength = 32767;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Black;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties24;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "Email";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(294, 33);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmail.TabIndex = 11;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 8;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "Email";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.AllowAnimations = true;
            this.btnChangePassword.AllowMouseEffects = true;
            this.btnChangePassword.AllowToggling = false;
            this.btnChangePassword.AnimationSpeed = 200;
            this.btnChangePassword.AutoGenerateColors = false;
            this.btnChangePassword.AutoRoundBorders = false;
            this.btnChangePassword.AutoSizeLeftIcon = true;
            this.btnChangePassword.AutoSizeRightIcon = true;
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.BackgroundImage")));
            this.btnChangePassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.ButtonText = "Change password";
            this.btnChangePassword.ButtonTextMarginLeft = 0;
            this.btnChangePassword.ColorContrastOnClick = 45;
            this.btnChangePassword.ColorContrastOnHover = 45;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnChangePassword.CustomizableEdges = borderEdges6;
            this.btnChangePassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangePassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangePassword.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangePassword.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangePassword.IconMarginLeft = 11;
            this.btnChangePassword.IconPadding = 10;
            this.btnChangePassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangePassword.IconSize = 25;
            this.btnChangePassword.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.IdleBorderRadius = 15;
            this.btnChangePassword.IdleBorderThickness = 1;
            this.btnChangePassword.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.IdleIconLeftImage = null;
            this.btnChangePassword.IdleIconRightImage = null;
            this.btnChangePassword.IndicateFocus = false;
            this.btnChangePassword.Location = new System.Drawing.Point(44, 315);
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.OnDisabledState.BorderRadius = 15;
            this.btnChangePassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnDisabledState.BorderThickness = 1;
            this.btnChangePassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.OnDisabledState.IconLeftImage = null;
            this.btnChangePassword.OnDisabledState.IconRightImage = null;
            this.btnChangePassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.BorderRadius = 15;
            this.btnChangePassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.onHoverState.BorderThickness = 1;
            this.btnChangePassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.onHoverState.IconLeftImage = null;
            this.btnChangePassword.onHoverState.IconRightImage = null;
            this.btnChangePassword.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.OnIdleState.BorderRadius = 15;
            this.btnChangePassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnIdleState.BorderThickness = 1;
            this.btnChangePassword.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChangePassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.IconLeftImage = null;
            this.btnChangePassword.OnIdleState.IconRightImage = null;
            this.btnChangePassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangePassword.OnPressedState.BorderRadius = 15;
            this.btnChangePassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnPressedState.BorderThickness = 1;
            this.btnChangePassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChangePassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnPressedState.IconLeftImage = null;
            this.btnChangePassword.OnPressedState.IconRightImage = null;
            this.btnChangePassword.Size = new System.Drawing.Size(294, 35);
            this.btnChangePassword.TabIndex = 15;
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangePassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangePassword.TextMarginLeft = 0;
            this.btnChangePassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.UseDefaultRadiusAndThickness = true;
            this.btnChangePassword.Click += new System.EventHandler(this.btnChangePassword_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(139, 369);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(73, 16);
            this.bunifuLabel4.TabIndex = 16;
            this.bunifuLabel4.Text = "No account?";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnSignIn
            // 
            this.btnSignIn.AllowAnimations = true;
            this.btnSignIn.AllowMouseEffects = true;
            this.btnSignIn.AllowToggling = false;
            this.btnSignIn.AnimationSpeed = 200;
            this.btnSignIn.AutoGenerateColors = false;
            this.btnSignIn.AutoRoundBorders = false;
            this.btnSignIn.AutoSizeLeftIcon = true;
            this.btnSignIn.AutoSizeRightIcon = true;
            this.btnSignIn.BackColor = System.Drawing.Color.Transparent;
            this.btnSignIn.BackColor1 = System.Drawing.Color.White;
            this.btnSignIn.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignIn.BackgroundImage")));
            this.btnSignIn.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignIn.ButtonText = "Log In";
            this.btnSignIn.ButtonTextMarginLeft = 0;
            this.btnSignIn.ColorContrastOnClick = 45;
            this.btnSignIn.ColorContrastOnHover = 45;
            this.btnSignIn.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnSignIn.CustomizableEdges = borderEdges7;
            this.btnSignIn.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignIn.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignIn.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignIn.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignIn.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignIn.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSignIn.ForeColor = System.Drawing.Color.Blue;
            this.btnSignIn.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignIn.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignIn.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignIn.IconMarginLeft = 11;
            this.btnSignIn.IconPadding = 10;
            this.btnSignIn.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignIn.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignIn.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignIn.IconSize = 25;
            this.btnSignIn.IdleBorderColor = System.Drawing.Color.White;
            this.btnSignIn.IdleBorderRadius = 1;
            this.btnSignIn.IdleBorderThickness = 1;
            this.btnSignIn.IdleFillColor = System.Drawing.Color.White;
            this.btnSignIn.IdleIconLeftImage = null;
            this.btnSignIn.IdleIconRightImage = null;
            this.btnSignIn.IndicateFocus = false;
            this.btnSignIn.Location = new System.Drawing.Point(83, 367);
            this.btnSignIn.Name = "btnSignIn";
            this.btnSignIn.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignIn.OnDisabledState.BorderRadius = 1;
            this.btnSignIn.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignIn.OnDisabledState.BorderThickness = 1;
            this.btnSignIn.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignIn.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignIn.OnDisabledState.IconLeftImage = null;
            this.btnSignIn.OnDisabledState.IconRightImage = null;
            this.btnSignIn.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSignIn.onHoverState.BorderRadius = 1;
            this.btnSignIn.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignIn.onHoverState.BorderThickness = 1;
            this.btnSignIn.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnSignIn.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSignIn.onHoverState.IconLeftImage = null;
            this.btnSignIn.onHoverState.IconRightImage = null;
            this.btnSignIn.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSignIn.OnIdleState.BorderRadius = 1;
            this.btnSignIn.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignIn.OnIdleState.BorderThickness = 1;
            this.btnSignIn.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnSignIn.OnIdleState.ForeColor = System.Drawing.Color.Blue;
            this.btnSignIn.OnIdleState.IconLeftImage = null;
            this.btnSignIn.OnIdleState.IconRightImage = null;
            this.btnSignIn.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSignIn.OnPressedState.BorderRadius = 1;
            this.btnSignIn.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignIn.OnPressedState.BorderThickness = 1;
            this.btnSignIn.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnSignIn.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnSignIn.OnPressedState.IconLeftImage = null;
            this.btnSignIn.OnPressedState.IconRightImage = null;
            this.btnSignIn.Size = new System.Drawing.Size(57, 21);
            this.btnSignIn.TabIndex = 17;
            this.btnSignIn.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignIn.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignIn.TextMarginLeft = 0;
            this.btnSignIn.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignIn.UseDefaultRadiusAndThickness = true;
            this.btnSignIn.Click += new System.EventHandler(this.btnSignIn_Click);
            // 
            // btnSignUp
            // 
            this.btnSignUp.AllowAnimations = true;
            this.btnSignUp.AllowMouseEffects = true;
            this.btnSignUp.AllowToggling = false;
            this.btnSignUp.AnimationSpeed = 200;
            this.btnSignUp.AutoGenerateColors = false;
            this.btnSignUp.AutoRoundBorders = false;
            this.btnSignUp.AutoSizeLeftIcon = true;
            this.btnSignUp.AutoSizeRightIcon = true;
            this.btnSignUp.BackColor = System.Drawing.Color.Transparent;
            this.btnSignUp.BackColor1 = System.Drawing.Color.White;
            this.btnSignUp.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignUp.BackgroundImage")));
            this.btnSignUp.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.ButtonText = "Sign Up";
            this.btnSignUp.ButtonTextMarginLeft = 0;
            this.btnSignUp.ColorContrastOnClick = 45;
            this.btnSignUp.ColorContrastOnHover = 45;
            this.btnSignUp.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnSignUp.CustomizableEdges = borderEdges8;
            this.btnSignUp.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignUp.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUp.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUp.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignUp.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSignUp.ForeColor = System.Drawing.Color.Blue;
            this.btnSignUp.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignUp.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignUp.IconMarginLeft = 11;
            this.btnSignUp.IconPadding = 10;
            this.btnSignUp.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignUp.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSignUp.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignUp.IconSize = 25;
            this.btnSignUp.IdleBorderColor = System.Drawing.Color.White;
            this.btnSignUp.IdleBorderRadius = 1;
            this.btnSignUp.IdleBorderThickness = 1;
            this.btnSignUp.IdleFillColor = System.Drawing.Color.White;
            this.btnSignUp.IdleIconLeftImage = null;
            this.btnSignUp.IdleIconRightImage = null;
            this.btnSignUp.IndicateFocus = false;
            this.btnSignUp.Location = new System.Drawing.Point(218, 367);
            this.btnSignUp.Name = "btnSignUp";
            this.btnSignUp.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignUp.OnDisabledState.BorderRadius = 1;
            this.btnSignUp.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnDisabledState.BorderThickness = 1;
            this.btnSignUp.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignUp.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignUp.OnDisabledState.IconLeftImage = null;
            this.btnSignUp.OnDisabledState.IconRightImage = null;
            this.btnSignUp.onHoverState.BorderColor = System.Drawing.Color.White;
            this.btnSignUp.onHoverState.BorderRadius = 1;
            this.btnSignUp.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.onHoverState.BorderThickness = 1;
            this.btnSignUp.onHoverState.FillColor = System.Drawing.Color.White;
            this.btnSignUp.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSignUp.onHoverState.IconLeftImage = null;
            this.btnSignUp.onHoverState.IconRightImage = null;
            this.btnSignUp.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnSignUp.OnIdleState.BorderRadius = 1;
            this.btnSignUp.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnIdleState.BorderThickness = 1;
            this.btnSignUp.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnSignUp.OnIdleState.ForeColor = System.Drawing.Color.Blue;
            this.btnSignUp.OnIdleState.IconLeftImage = null;
            this.btnSignUp.OnIdleState.IconRightImage = null;
            this.btnSignUp.OnPressedState.BorderColor = System.Drawing.Color.White;
            this.btnSignUp.OnPressedState.BorderRadius = 1;
            this.btnSignUp.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignUp.OnPressedState.BorderThickness = 1;
            this.btnSignUp.OnPressedState.FillColor = System.Drawing.Color.White;
            this.btnSignUp.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnSignUp.OnPressedState.IconLeftImage = null;
            this.btnSignUp.OnPressedState.IconRightImage = null;
            this.btnSignUp.Size = new System.Drawing.Size(57, 21);
            this.btnSignUp.TabIndex = 18;
            this.btnSignUp.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignUp.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignUp.TextMarginLeft = 0;
            this.btnSignUp.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignUp.UseDefaultRadiusAndThickness = true;
            this.btnSignUp.Click += new System.EventHandler(this.btnSignUp_Click);
            // 
            // frmForgetPassword
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(401, 408);
            this.Controls.Add(this.btnSignUp);
            this.Controls.Add(this.btnSignIn);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.btnChangePassword);
            this.Controls.Add(this.btnSend);
            this.Controls.Add(this.txtSecureCode);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuPanel1);
            this.ForeColor = System.Drawing.Color.Black;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmForgetPassword";
            this.Text = "frmForgetPassword";
            this.Load += new System.EventHandler(this.frmForgetPassword_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSend;
        private Bunifu.UI.WinForms.BunifuTextBox txtSecureCode;
        private Bunifu.UI.WinForms.BunifuTextBox txtPassword;
        private Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangePassword;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignIn;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignUp;
    }
}