namespace NguyenTienDat_10122119
{
    partial class frmSettings
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSettings));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.btnResetAll = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnBasic = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSecurity = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnController = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRecipent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUntended = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.panel1.Controls.Add(this.btnResetAll);
            this.panel1.Controls.Add(this.bunifuLabel1);
            this.panel1.Controls.Add(this.btnBasic);
            this.panel1.Controls.Add(this.btnSecurity);
            this.panel1.Controls.Add(this.btnController);
            this.panel1.Controls.Add(this.btnRecipent);
            this.panel1.Controls.Add(this.btnUntended);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(167, 364);
            this.panel1.TabIndex = 0;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // btnResetAll
            // 
            this.btnResetAll.AllowAnimations = true;
            this.btnResetAll.AllowMouseEffects = true;
            this.btnResetAll.AllowToggling = false;
            this.btnResetAll.AnimationSpeed = 200;
            this.btnResetAll.AutoGenerateColors = false;
            this.btnResetAll.AutoRoundBorders = false;
            this.btnResetAll.AutoSizeLeftIcon = true;
            this.btnResetAll.AutoSizeRightIcon = true;
            this.btnResetAll.BackColor = System.Drawing.Color.Transparent;
            this.btnResetAll.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnResetAll.BackgroundImage")));
            this.btnResetAll.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResetAll.ButtonText = "Reset All";
            this.btnResetAll.ButtonTextMarginLeft = 0;
            this.btnResetAll.ColorContrastOnClick = 45;
            this.btnResetAll.ColorContrastOnHover = 45;
            this.btnResetAll.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnResetAll.CustomizableEdges = borderEdges1;
            this.btnResetAll.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnResetAll.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnResetAll.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnResetAll.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnResetAll.ForeColor = System.Drawing.Color.Black;
            this.btnResetAll.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnResetAll.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnResetAll.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnResetAll.IconMarginLeft = 11;
            this.btnResetAll.IconPadding = 10;
            this.btnResetAll.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnResetAll.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnResetAll.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnResetAll.IconSize = 25;
            this.btnResetAll.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.IdleBorderRadius = 1;
            this.btnResetAll.IdleBorderThickness = 1;
            this.btnResetAll.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.IdleIconLeftImage = null;
            this.btnResetAll.IdleIconRightImage = null;
            this.btnResetAll.IndicateFocus = false;
            this.btnResetAll.Location = new System.Drawing.Point(16, 332);
            this.btnResetAll.Name = "btnResetAll";
            this.btnResetAll.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnDisabledState.BorderRadius = 1;
            this.btnResetAll.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResetAll.OnDisabledState.BorderThickness = 1;
            this.btnResetAll.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnResetAll.OnDisabledState.IconLeftImage = null;
            this.btnResetAll.OnDisabledState.IconRightImage = null;
            this.btnResetAll.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.onHoverState.BorderRadius = 1;
            this.btnResetAll.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResetAll.onHoverState.BorderThickness = 1;
            this.btnResetAll.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(151)))), ((int)(((byte)(252)))));
            this.btnResetAll.onHoverState.IconLeftImage = null;
            this.btnResetAll.onHoverState.IconRightImage = null;
            this.btnResetAll.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnIdleState.BorderRadius = 1;
            this.btnResetAll.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResetAll.OnIdleState.BorderThickness = 1;
            this.btnResetAll.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnResetAll.OnIdleState.IconLeftImage = null;
            this.btnResetAll.OnIdleState.IconRightImage = null;
            this.btnResetAll.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnPressedState.BorderRadius = 1;
            this.btnResetAll.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnResetAll.OnPressedState.BorderThickness = 1;
            this.btnResetAll.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnResetAll.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(151)))), ((int)(((byte)(252)))));
            this.btnResetAll.OnPressedState.IconLeftImage = null;
            this.btnResetAll.OnPressedState.IconRightImage = null;
            this.btnResetAll.Size = new System.Drawing.Size(96, 29);
            this.btnResetAll.TabIndex = 0;
            this.btnResetAll.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnResetAll.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnResetAll.TextMarginLeft = 0;
            this.btnResetAll.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnResetAll.UseDefaultRadiusAndThickness = true;
            this.btnResetAll.Click += new System.EventHandler(this.btnResetAll_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.Location = new System.Drawing.Point(29, 24);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(77, 25);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Settings";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnBasic
            // 
            this.btnBasic.AllowAnimations = true;
            this.btnBasic.AllowMouseEffects = true;
            this.btnBasic.AllowToggling = false;
            this.btnBasic.AnimationSpeed = 200;
            this.btnBasic.AutoGenerateColors = false;
            this.btnBasic.AutoRoundBorders = false;
            this.btnBasic.AutoSizeLeftIcon = true;
            this.btnBasic.AutoSizeRightIcon = true;
            this.btnBasic.BackColor = System.Drawing.Color.Transparent;
            this.btnBasic.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnBasic.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBasic.BackgroundImage")));
            this.btnBasic.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBasic.ButtonText = "Basic";
            this.btnBasic.ButtonTextMarginLeft = 0;
            this.btnBasic.ColorContrastOnClick = 45;
            this.btnBasic.ColorContrastOnHover = 45;
            this.btnBasic.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnBasic.CustomizableEdges = borderEdges2;
            this.btnBasic.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBasic.DisabledBorderColor = System.Drawing.Color.White;
            this.btnBasic.DisabledFillColor = System.Drawing.Color.White;
            this.btnBasic.DisabledForecolor = System.Drawing.Color.White;
            this.btnBasic.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBasic.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnBasic.ForeColor = System.Drawing.Color.Black;
            this.btnBasic.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBasic.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBasic.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBasic.IconMarginLeft = 11;
            this.btnBasic.IconPadding = 10;
            this.btnBasic.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBasic.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBasic.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBasic.IconSize = 25;
            this.btnBasic.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnBasic.IdleBorderRadius = 10;
            this.btnBasic.IdleBorderThickness = 1;
            this.btnBasic.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnBasic.IdleIconLeftImage = null;
            this.btnBasic.IdleIconRightImage = null;
            this.btnBasic.IndicateFocus = false;
            this.btnBasic.Location = new System.Drawing.Point(3, 269);
            this.btnBasic.Name = "btnBasic";
            this.btnBasic.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnBasic.OnDisabledState.BorderRadius = 10;
            this.btnBasic.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBasic.OnDisabledState.BorderThickness = 1;
            this.btnBasic.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnBasic.OnDisabledState.ForeColor = System.Drawing.Color.White;
            this.btnBasic.OnDisabledState.IconLeftImage = null;
            this.btnBasic.OnDisabledState.IconRightImage = null;
            this.btnBasic.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnBasic.onHoverState.BorderRadius = 10;
            this.btnBasic.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBasic.onHoverState.BorderThickness = 1;
            this.btnBasic.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnBasic.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnBasic.onHoverState.IconLeftImage = null;
            this.btnBasic.onHoverState.IconRightImage = null;
            this.btnBasic.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnBasic.OnIdleState.BorderRadius = 10;
            this.btnBasic.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBasic.OnIdleState.BorderThickness = 1;
            this.btnBasic.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnBasic.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnBasic.OnIdleState.IconLeftImage = null;
            this.btnBasic.OnIdleState.IconRightImage = null;
            this.btnBasic.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnBasic.OnPressedState.BorderRadius = 10;
            this.btnBasic.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBasic.OnPressedState.BorderThickness = 1;
            this.btnBasic.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnBasic.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnBasic.OnPressedState.IconLeftImage = null;
            this.btnBasic.OnPressedState.IconRightImage = null;
            this.btnBasic.Size = new System.Drawing.Size(131, 45);
            this.btnBasic.TabIndex = 0;
            this.btnBasic.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBasic.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBasic.TextMarginLeft = 0;
            this.btnBasic.TextPadding = new System.Windows.Forms.Padding(-21, 0, 0, 0);
            this.btnBasic.UseDefaultRadiusAndThickness = true;
            this.btnBasic.Click += new System.EventHandler(this.btnBasic_Click);
            // 
            // btnSecurity
            // 
            this.btnSecurity.AllowAnimations = true;
            this.btnSecurity.AllowMouseEffects = true;
            this.btnSecurity.AllowToggling = false;
            this.btnSecurity.AnimationSpeed = 200;
            this.btnSecurity.AutoGenerateColors = false;
            this.btnSecurity.AutoRoundBorders = false;
            this.btnSecurity.AutoSizeLeftIcon = true;
            this.btnSecurity.AutoSizeRightIcon = true;
            this.btnSecurity.BackColor = System.Drawing.Color.Transparent;
            this.btnSecurity.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnSecurity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSecurity.BackgroundImage")));
            this.btnSecurity.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSecurity.ButtonText = "Security";
            this.btnSecurity.ButtonTextMarginLeft = 0;
            this.btnSecurity.ColorContrastOnClick = 45;
            this.btnSecurity.ColorContrastOnHover = 45;
            this.btnSecurity.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnSecurity.CustomizableEdges = borderEdges3;
            this.btnSecurity.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSecurity.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSecurity.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSecurity.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSecurity.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSecurity.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSecurity.ForeColor = System.Drawing.Color.Black;
            this.btnSecurity.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSecurity.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSecurity.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSecurity.IconMarginLeft = 11;
            this.btnSecurity.IconPadding = 10;
            this.btnSecurity.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSecurity.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSecurity.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSecurity.IconSize = 25;
            this.btnSecurity.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnSecurity.IdleBorderRadius = 10;
            this.btnSecurity.IdleBorderThickness = 1;
            this.btnSecurity.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnSecurity.IdleIconLeftImage = null;
            this.btnSecurity.IdleIconRightImage = null;
            this.btnSecurity.IndicateFocus = false;
            this.btnSecurity.Location = new System.Drawing.Point(3, 218);
            this.btnSecurity.Name = "btnSecurity";
            this.btnSecurity.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSecurity.OnDisabledState.BorderRadius = 10;
            this.btnSecurity.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSecurity.OnDisabledState.BorderThickness = 1;
            this.btnSecurity.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSecurity.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSecurity.OnDisabledState.IconLeftImage = null;
            this.btnSecurity.OnDisabledState.IconRightImage = null;
            this.btnSecurity.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSecurity.onHoverState.BorderRadius = 10;
            this.btnSecurity.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSecurity.onHoverState.BorderThickness = 1;
            this.btnSecurity.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnSecurity.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSecurity.onHoverState.IconLeftImage = null;
            this.btnSecurity.onHoverState.IconRightImage = null;
            this.btnSecurity.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnSecurity.OnIdleState.BorderRadius = 10;
            this.btnSecurity.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSecurity.OnIdleState.BorderThickness = 1;
            this.btnSecurity.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnSecurity.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnSecurity.OnIdleState.IconLeftImage = null;
            this.btnSecurity.OnIdleState.IconRightImage = null;
            this.btnSecurity.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnSecurity.OnPressedState.BorderRadius = 10;
            this.btnSecurity.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSecurity.OnPressedState.BorderThickness = 1;
            this.btnSecurity.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnSecurity.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnSecurity.OnPressedState.IconLeftImage = null;
            this.btnSecurity.OnPressedState.IconRightImage = null;
            this.btnSecurity.Size = new System.Drawing.Size(131, 45);
            this.btnSecurity.TabIndex = 0;
            this.btnSecurity.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSecurity.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSecurity.TextMarginLeft = 0;
            this.btnSecurity.TextPadding = new System.Windows.Forms.Padding(-13, 0, 0, 0);
            this.btnSecurity.UseDefaultRadiusAndThickness = true;
            this.btnSecurity.Click += new System.EventHandler(this.btnSecurity_Click);
            // 
            // btnController
            // 
            this.btnController.AllowAnimations = true;
            this.btnController.AllowMouseEffects = true;
            this.btnController.AllowToggling = false;
            this.btnController.AnimationSpeed = 200;
            this.btnController.AutoGenerateColors = false;
            this.btnController.AutoRoundBorders = false;
            this.btnController.AutoSizeLeftIcon = true;
            this.btnController.AutoSizeRightIcon = true;
            this.btnController.BackColor = System.Drawing.Color.Transparent;
            this.btnController.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnController.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnController.BackgroundImage")));
            this.btnController.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnController.ButtonText = "Controller";
            this.btnController.ButtonTextMarginLeft = 0;
            this.btnController.ColorContrastOnClick = 45;
            this.btnController.ColorContrastOnHover = 45;
            this.btnController.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnController.CustomizableEdges = borderEdges4;
            this.btnController.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnController.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnController.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnController.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnController.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnController.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnController.ForeColor = System.Drawing.Color.Black;
            this.btnController.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnController.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnController.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnController.IconMarginLeft = 11;
            this.btnController.IconPadding = 10;
            this.btnController.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnController.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnController.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnController.IconSize = 25;
            this.btnController.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnController.IdleBorderRadius = 10;
            this.btnController.IdleBorderThickness = 1;
            this.btnController.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnController.IdleIconLeftImage = null;
            this.btnController.IdleIconRightImage = null;
            this.btnController.IndicateFocus = false;
            this.btnController.Location = new System.Drawing.Point(3, 167);
            this.btnController.Name = "btnController";
            this.btnController.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnController.OnDisabledState.BorderRadius = 10;
            this.btnController.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnController.OnDisabledState.BorderThickness = 1;
            this.btnController.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnController.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnController.OnDisabledState.IconLeftImage = null;
            this.btnController.OnDisabledState.IconRightImage = null;
            this.btnController.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnController.onHoverState.BorderRadius = 10;
            this.btnController.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnController.onHoverState.BorderThickness = 1;
            this.btnController.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnController.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnController.onHoverState.IconLeftImage = null;
            this.btnController.onHoverState.IconRightImage = null;
            this.btnController.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnController.OnIdleState.BorderRadius = 10;
            this.btnController.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnController.OnIdleState.BorderThickness = 1;
            this.btnController.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnController.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnController.OnIdleState.IconLeftImage = null;
            this.btnController.OnIdleState.IconRightImage = null;
            this.btnController.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnController.OnPressedState.BorderRadius = 10;
            this.btnController.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnController.OnPressedState.BorderThickness = 1;
            this.btnController.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnController.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnController.OnPressedState.IconLeftImage = null;
            this.btnController.OnPressedState.IconRightImage = null;
            this.btnController.Size = new System.Drawing.Size(131, 45);
            this.btnController.TabIndex = 0;
            this.btnController.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnController.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnController.TextMarginLeft = 0;
            this.btnController.TextPadding = new System.Windows.Forms.Padding(-8, 0, 0, 0);
            this.btnController.UseDefaultRadiusAndThickness = true;
            this.btnController.Click += new System.EventHandler(this.btnController_Click);
            // 
            // btnRecipent
            // 
            this.btnRecipent.AllowAnimations = true;
            this.btnRecipent.AllowMouseEffects = true;
            this.btnRecipent.AllowToggling = false;
            this.btnRecipent.AnimationSpeed = 200;
            this.btnRecipent.AutoGenerateColors = false;
            this.btnRecipent.AutoRoundBorders = false;
            this.btnRecipent.AutoSizeLeftIcon = true;
            this.btnRecipent.AutoSizeRightIcon = true;
            this.btnRecipent.BackColor = System.Drawing.Color.Transparent;
            this.btnRecipent.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnRecipent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRecipent.BackgroundImage")));
            this.btnRecipent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecipent.ButtonText = "Recipent";
            this.btnRecipent.ButtonTextMarginLeft = 0;
            this.btnRecipent.ColorContrastOnClick = 45;
            this.btnRecipent.ColorContrastOnHover = 45;
            this.btnRecipent.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnRecipent.CustomizableEdges = borderEdges5;
            this.btnRecipent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRecipent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecipent.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecipent.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecipent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRecipent.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRecipent.ForeColor = System.Drawing.Color.Black;
            this.btnRecipent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRecipent.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecipent.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRecipent.IconMarginLeft = 11;
            this.btnRecipent.IconPadding = 10;
            this.btnRecipent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRecipent.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRecipent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRecipent.IconSize = 25;
            this.btnRecipent.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnRecipent.IdleBorderRadius = 10;
            this.btnRecipent.IdleBorderThickness = 1;
            this.btnRecipent.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnRecipent.IdleIconLeftImage = null;
            this.btnRecipent.IdleIconRightImage = null;
            this.btnRecipent.IndicateFocus = false;
            this.btnRecipent.Location = new System.Drawing.Point(3, 116);
            this.btnRecipent.Name = "btnRecipent";
            this.btnRecipent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecipent.OnDisabledState.BorderRadius = 10;
            this.btnRecipent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecipent.OnDisabledState.BorderThickness = 1;
            this.btnRecipent.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRecipent.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRecipent.OnDisabledState.IconLeftImage = null;
            this.btnRecipent.OnDisabledState.IconRightImage = null;
            this.btnRecipent.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRecipent.onHoverState.BorderRadius = 10;
            this.btnRecipent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecipent.onHoverState.BorderThickness = 1;
            this.btnRecipent.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnRecipent.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnRecipent.onHoverState.IconLeftImage = null;
            this.btnRecipent.onHoverState.IconRightImage = null;
            this.btnRecipent.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnRecipent.OnIdleState.BorderRadius = 10;
            this.btnRecipent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecipent.OnIdleState.BorderThickness = 1;
            this.btnRecipent.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnRecipent.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnRecipent.OnIdleState.IconLeftImage = null;
            this.btnRecipent.OnIdleState.IconRightImage = null;
            this.btnRecipent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnRecipent.OnPressedState.BorderRadius = 10;
            this.btnRecipent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRecipent.OnPressedState.BorderThickness = 1;
            this.btnRecipent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnRecipent.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnRecipent.OnPressedState.IconLeftImage = null;
            this.btnRecipent.OnPressedState.IconRightImage = null;
            this.btnRecipent.Size = new System.Drawing.Size(131, 45);
            this.btnRecipent.TabIndex = 0;
            this.btnRecipent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRecipent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRecipent.TextMarginLeft = 0;
            this.btnRecipent.TextPadding = new System.Windows.Forms.Padding(-10, 0, 0, 0);
            this.btnRecipent.UseDefaultRadiusAndThickness = true;
            this.btnRecipent.Click += new System.EventHandler(this.btnRecipient_Click);
            // 
            // btnUntended
            // 
            this.btnUntended.AllowAnimations = false;
            this.btnUntended.AllowMouseEffects = true;
            this.btnUntended.AllowToggling = false;
            this.btnUntended.AnimationSpeed = 200;
            this.btnUntended.AutoGenerateColors = false;
            this.btnUntended.AutoRoundBorders = false;
            this.btnUntended.AutoSizeLeftIcon = true;
            this.btnUntended.AutoSizeRightIcon = true;
            this.btnUntended.BackColor = System.Drawing.Color.Transparent;
            this.btnUntended.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnUntended.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUntended.BackgroundImage")));
            this.btnUntended.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUntended.ButtonText = "Unattended";
            this.btnUntended.ButtonTextMarginLeft = 0;
            this.btnUntended.ColorContrastOnClick = 45;
            this.btnUntended.ColorContrastOnHover = 45;
            this.btnUntended.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnUntended.CustomizableEdges = borderEdges6;
            this.btnUntended.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUntended.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUntended.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUntended.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUntended.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Hover;
            this.btnUntended.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnUntended.ForeColor = System.Drawing.Color.Black;
            this.btnUntended.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUntended.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUntended.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUntended.IconMarginLeft = 11;
            this.btnUntended.IconPadding = 10;
            this.btnUntended.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUntended.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUntended.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUntended.IconSize = 25;
            this.btnUntended.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnUntended.IdleBorderRadius = 10;
            this.btnUntended.IdleBorderThickness = 1;
            this.btnUntended.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnUntended.IdleIconLeftImage = null;
            this.btnUntended.IdleIconRightImage = null;
            this.btnUntended.IndicateFocus = false;
            this.btnUntended.Location = new System.Drawing.Point(3, 64);
            this.btnUntended.Margin = new System.Windows.Forms.Padding(0);
            this.btnUntended.Name = "btnUntended";
            this.btnUntended.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUntended.OnDisabledState.BorderRadius = 10;
            this.btnUntended.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUntended.OnDisabledState.BorderThickness = 1;
            this.btnUntended.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUntended.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUntended.OnDisabledState.IconLeftImage = null;
            this.btnUntended.OnDisabledState.IconRightImage = null;
            this.btnUntended.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnUntended.onHoverState.BorderRadius = 10;
            this.btnUntended.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUntended.onHoverState.BorderThickness = 1;
            this.btnUntended.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.btnUntended.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnUntended.onHoverState.IconLeftImage = null;
            this.btnUntended.onHoverState.IconRightImage = null;
            this.btnUntended.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnUntended.OnIdleState.BorderRadius = 10;
            this.btnUntended.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUntended.OnIdleState.BorderThickness = 1;
            this.btnUntended.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(247)))), ((int)(((byte)(251)))));
            this.btnUntended.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnUntended.OnIdleState.IconLeftImage = null;
            this.btnUntended.OnIdleState.IconRightImage = null;
            this.btnUntended.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnUntended.OnPressedState.BorderRadius = 10;
            this.btnUntended.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUntended.OnPressedState.BorderThickness = 1;
            this.btnUntended.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.btnUntended.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnUntended.OnPressedState.IconLeftImage = null;
            this.btnUntended.OnPressedState.IconRightImage = null;
            this.btnUntended.Size = new System.Drawing.Size(131, 49);
            this.btnUntended.TabIndex = 0;
            this.btnUntended.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUntended.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUntended.TextMarginLeft = 0;
            this.btnUntended.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUntended.UseDefaultRadiusAndThickness = true;
            this.btnUntended.Click += new System.EventHandler(this.btnUntended_Click);
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel2.Location = new System.Drawing.Point(173, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(440, 364);
            this.panel2.TabIndex = 1;
            // 
            // frmSettings
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.ClientSize = new System.Drawing.Size(613, 364);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmSettings";
            this.Text = "frmSettings";
            this.Load += new System.EventHandler(this.frmSettings_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUntended;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBasic;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSecurity;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnController;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRecipent;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnResetAll;
    }
}