namespace NguyenTienDat_10122119
{
    partial class frmSuccessfully
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmSuccessfully));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.imgProfile = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.pnlMore = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnEditProfilePicture = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogOut = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnChangePassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnChangeUsername = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManagementCenter = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnMore = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblEmail = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblName = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imgProfile)).BeginInit();
            this.pnlMore.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 25;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.imgProfile);
            this.bunifuPanel1.Controls.Add(this.pnlMore);
            this.bunifuPanel1.Controls.Add(this.btnMore);
            this.bunifuPanel1.Controls.Add(this.lblEmail);
            this.bunifuPanel1.Controls.Add(this.lblName);
            this.bunifuPanel1.Location = new System.Drawing.Point(30, 12);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(506, 256);
            this.bunifuPanel1.TabIndex = 1;
            this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
            // 
            // imgProfile
            // 
            this.imgProfile.AllowFocused = false;
            this.imgProfile.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.imgProfile.AutoSizeHeight = true;
            this.imgProfile.BorderRadius = 56;
            this.imgProfile.Image = global::NguyenTienDat_10122119.Properties.Resources.icons8_user_96;
            this.imgProfile.IsCircle = true;
            this.imgProfile.Location = new System.Drawing.Point(45, 27);
            this.imgProfile.Name = "imgProfile";
            this.imgProfile.Size = new System.Drawing.Size(112, 112);
            this.imgProfile.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.imgProfile.TabIndex = 6;
            this.imgProfile.TabStop = false;
            this.imgProfile.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.imgProfile.Click += new System.EventHandler(this.imgProfile_Click);
            // 
            // pnlMore
            // 
            this.pnlMore.BackgroundColor = System.Drawing.Color.Transparent;
            this.pnlMore.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlMore.BackgroundImage")));
            this.pnlMore.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlMore.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.pnlMore.BorderRadius = 15;
            this.pnlMore.BorderThickness = 0;
            this.pnlMore.Controls.Add(this.btnEditProfilePicture);
            this.pnlMore.Controls.Add(this.btnLogOut);
            this.pnlMore.Controls.Add(this.btnChangePassword);
            this.pnlMore.Controls.Add(this.btnChangeUsername);
            this.pnlMore.Controls.Add(this.btnManagementCenter);
            this.pnlMore.Location = new System.Drawing.Point(305, 27);
            this.pnlMore.Margin = new System.Windows.Forms.Padding(0);
            this.pnlMore.Name = "pnlMore";
            this.pnlMore.ShowBorders = true;
            this.pnlMore.Size = new System.Drawing.Size(164, 204);
            this.pnlMore.TabIndex = 3;
            // 
            // btnEditProfilePicture
            // 
            this.btnEditProfilePicture.AllowAnimations = true;
            this.btnEditProfilePicture.AllowMouseEffects = true;
            this.btnEditProfilePicture.AllowToggling = false;
            this.btnEditProfilePicture.AnimationSpeed = 200;
            this.btnEditProfilePicture.AutoGenerateColors = false;
            this.btnEditProfilePicture.AutoRoundBorders = false;
            this.btnEditProfilePicture.AutoSizeLeftIcon = true;
            this.btnEditProfilePicture.AutoSizeRightIcon = true;
            this.btnEditProfilePicture.BackColor = System.Drawing.Color.Transparent;
            this.btnEditProfilePicture.BackColor1 = System.Drawing.Color.White;
            this.btnEditProfilePicture.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEditProfilePicture.BackgroundImage")));
            this.btnEditProfilePicture.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProfilePicture.ButtonText = "Edit profile picture";
            this.btnEditProfilePicture.ButtonTextMarginLeft = 0;
            this.btnEditProfilePicture.ColorContrastOnClick = 45;
            this.btnEditProfilePicture.ColorContrastOnHover = 45;
            this.btnEditProfilePicture.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnEditProfilePicture.CustomizableEdges = borderEdges1;
            this.btnEditProfilePicture.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEditProfilePicture.DisabledBorderColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.DisabledFillColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.DisabledForecolor = System.Drawing.Color.Black;
            this.btnEditProfilePicture.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEditProfilePicture.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEditProfilePicture.ForeColor = System.Drawing.Color.Black;
            this.btnEditProfilePicture.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEditProfilePicture.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditProfilePicture.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnEditProfilePicture.IconMarginLeft = 11;
            this.btnEditProfilePicture.IconPadding = 10;
            this.btnEditProfilePicture.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEditProfilePicture.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEditProfilePicture.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnEditProfilePicture.IconSize = 25;
            this.btnEditProfilePicture.IdleBorderColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.IdleBorderRadius = 1;
            this.btnEditProfilePicture.IdleBorderThickness = 1;
            this.btnEditProfilePicture.IdleFillColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_user_24;
            this.btnEditProfilePicture.IdleIconRightImage = null;
            this.btnEditProfilePicture.IndicateFocus = false;
            this.btnEditProfilePicture.Location = new System.Drawing.Point(3, 123);
            this.btnEditProfilePicture.Name = "btnEditProfilePicture";
            this.btnEditProfilePicture.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.OnDisabledState.BorderRadius = 1;
            this.btnEditProfilePicture.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProfilePicture.OnDisabledState.BorderThickness = 1;
            this.btnEditProfilePicture.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btnEditProfilePicture.OnDisabledState.IconLeftImage = null;
            this.btnEditProfilePicture.OnDisabledState.IconRightImage = null;
            this.btnEditProfilePicture.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnEditProfilePicture.onHoverState.BorderRadius = 1;
            this.btnEditProfilePicture.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProfilePicture.onHoverState.BorderThickness = 1;
            this.btnEditProfilePicture.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnEditProfilePicture.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.onHoverState.IconLeftImage = null;
            this.btnEditProfilePicture.onHoverState.IconRightImage = null;
            this.btnEditProfilePicture.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.OnIdleState.BorderRadius = 1;
            this.btnEditProfilePicture.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProfilePicture.OnIdleState.BorderThickness = 1;
            this.btnEditProfilePicture.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnEditProfilePicture.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_user_24;
            this.btnEditProfilePicture.OnIdleState.IconRightImage = null;
            this.btnEditProfilePicture.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnEditProfilePicture.OnPressedState.BorderRadius = 1;
            this.btnEditProfilePicture.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEditProfilePicture.OnPressedState.BorderThickness = 1;
            this.btnEditProfilePicture.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnEditProfilePicture.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEditProfilePicture.OnPressedState.IconLeftImage = null;
            this.btnEditProfilePicture.OnPressedState.IconRightImage = null;
            this.btnEditProfilePicture.Size = new System.Drawing.Size(164, 36);
            this.btnEditProfilePicture.TabIndex = 7;
            this.btnEditProfilePicture.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEditProfilePicture.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEditProfilePicture.TextMarginLeft = 0;
            this.btnEditProfilePicture.TextPadding = new System.Windows.Forms.Padding(-10, 0, 0, 0);
            this.btnEditProfilePicture.UseDefaultRadiusAndThickness = true;
            this.btnEditProfilePicture.Click += new System.EventHandler(this.btnEditProfilePicture_Click);
            // 
            // btnLogOut
            // 
            this.btnLogOut.AllowAnimations = true;
            this.btnLogOut.AllowMouseEffects = true;
            this.btnLogOut.AllowToggling = false;
            this.btnLogOut.AnimationSpeed = 200;
            this.btnLogOut.AutoGenerateColors = false;
            this.btnLogOut.AutoRoundBorders = false;
            this.btnLogOut.AutoSizeLeftIcon = true;
            this.btnLogOut.AutoSizeRightIcon = true;
            this.btnLogOut.BackColor = System.Drawing.Color.Transparent;
            this.btnLogOut.BackColor1 = System.Drawing.Color.White;
            this.btnLogOut.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogOut.BackgroundImage")));
            this.btnLogOut.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.ButtonText = "Log out";
            this.btnLogOut.ButtonTextMarginLeft = 0;
            this.btnLogOut.ColorContrastOnClick = 45;
            this.btnLogOut.ColorContrastOnHover = 45;
            this.btnLogOut.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLogOut.CustomizableEdges = borderEdges2;
            this.btnLogOut.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogOut.DisabledBorderColor = System.Drawing.Color.White;
            this.btnLogOut.DisabledFillColor = System.Drawing.Color.White;
            this.btnLogOut.DisabledForecolor = System.Drawing.Color.Black;
            this.btnLogOut.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnLogOut.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnLogOut.ForeColor = System.Drawing.Color.Black;
            this.btnLogOut.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogOut.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogOut.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnLogOut.IconMarginLeft = 11;
            this.btnLogOut.IconPadding = 10;
            this.btnLogOut.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogOut.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogOut.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnLogOut.IconSize = 25;
            this.btnLogOut.IdleBorderColor = System.Drawing.Color.White;
            this.btnLogOut.IdleBorderRadius = 10;
            this.btnLogOut.IdleBorderThickness = 1;
            this.btnLogOut.IdleFillColor = System.Drawing.Color.White;
            this.btnLogOut.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_log_out_32;
            this.btnLogOut.IdleIconRightImage = null;
            this.btnLogOut.IndicateFocus = false;
            this.btnLogOut.Location = new System.Drawing.Point(3, 165);
            this.btnLogOut.Margin = new System.Windows.Forms.Padding(0);
            this.btnLogOut.Name = "btnLogOut";
            this.btnLogOut.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnLogOut.OnDisabledState.BorderRadius = 10;
            this.btnLogOut.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnDisabledState.BorderThickness = 1;
            this.btnLogOut.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnLogOut.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btnLogOut.OnDisabledState.IconLeftImage = null;
            this.btnLogOut.OnDisabledState.IconRightImage = null;
            this.btnLogOut.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnLogOut.onHoverState.BorderRadius = 10;
            this.btnLogOut.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.onHoverState.BorderThickness = 1;
            this.btnLogOut.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnLogOut.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnLogOut.onHoverState.IconLeftImage = null;
            this.btnLogOut.onHoverState.IconRightImage = null;
            this.btnLogOut.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnLogOut.OnIdleState.BorderRadius = 10;
            this.btnLogOut.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnIdleState.BorderThickness = 1;
            this.btnLogOut.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLogOut.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnLogOut.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_log_out_32;
            this.btnLogOut.OnIdleState.IconRightImage = null;
            this.btnLogOut.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnLogOut.OnPressedState.BorderRadius = 10;
            this.btnLogOut.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogOut.OnPressedState.BorderThickness = 1;
            this.btnLogOut.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnLogOut.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogOut.OnPressedState.IconLeftImage = null;
            this.btnLogOut.OnPressedState.IconRightImage = null;
            this.btnLogOut.Size = new System.Drawing.Size(124, 36);
            this.btnLogOut.TabIndex = 0;
            this.btnLogOut.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnLogOut.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogOut.TextMarginLeft = 0;
            this.btnLogOut.TextPadding = new System.Windows.Forms.Padding(-10, 0, 0, 0);
            this.btnLogOut.UseDefaultRadiusAndThickness = true;
            this.btnLogOut.Click += new System.EventHandler(this.btnLogOut_Click);
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.AllowAnimations = true;
            this.btnChangePassword.AllowMouseEffects = true;
            this.btnChangePassword.AllowToggling = false;
            this.btnChangePassword.AnimationSpeed = 200;
            this.btnChangePassword.AutoGenerateColors = false;
            this.btnChangePassword.AutoRoundBorders = false;
            this.btnChangePassword.AutoSizeLeftIcon = true;
            this.btnChangePassword.AutoSizeRightIcon = true;
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BackColor1 = System.Drawing.Color.White;
            this.btnChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.BackgroundImage")));
            this.btnChangePassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.ButtonText = "Change password";
            this.btnChangePassword.ButtonTextMarginLeft = 0;
            this.btnChangePassword.ColorContrastOnClick = 45;
            this.btnChangePassword.ColorContrastOnHover = 45;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnChangePassword.CustomizableEdges = borderEdges3;
            this.btnChangePassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangePassword.DisabledBorderColor = System.Drawing.Color.White;
            this.btnChangePassword.DisabledFillColor = System.Drawing.Color.White;
            this.btnChangePassword.DisabledForecolor = System.Drawing.Color.Black;
            this.btnChangePassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangePassword.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangePassword.ForeColor = System.Drawing.Color.Black;
            this.btnChangePassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.IconMarginLeft = 11;
            this.btnChangePassword.IconPadding = 10;
            this.btnChangePassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.IconSize = 25;
            this.btnChangePassword.IdleBorderColor = System.Drawing.Color.White;
            this.btnChangePassword.IdleBorderRadius = 10;
            this.btnChangePassword.IdleBorderThickness = 1;
            this.btnChangePassword.IdleFillColor = System.Drawing.Color.White;
            this.btnChangePassword.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_lock_24;
            this.btnChangePassword.IdleIconRightImage = null;
            this.btnChangePassword.IndicateFocus = false;
            this.btnChangePassword.Location = new System.Drawing.Point(3, 81);
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnChangePassword.OnDisabledState.BorderRadius = 10;
            this.btnChangePassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnDisabledState.BorderThickness = 1;
            this.btnChangePassword.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnChangePassword.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btnChangePassword.OnDisabledState.IconLeftImage = null;
            this.btnChangePassword.OnDisabledState.IconRightImage = null;
            this.btnChangePassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.BorderRadius = 10;
            this.btnChangePassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.onHoverState.BorderThickness = 1;
            this.btnChangePassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangePassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.onHoverState.IconLeftImage = null;
            this.btnChangePassword.onHoverState.IconRightImage = null;
            this.btnChangePassword.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.BorderRadius = 10;
            this.btnChangePassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnIdleState.BorderThickness = 1;
            this.btnChangePassword.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnChangePassword.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_lock_24;
            this.btnChangePassword.OnIdleState.IconRightImage = null;
            this.btnChangePassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangePassword.OnPressedState.BorderRadius = 10;
            this.btnChangePassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnPressedState.BorderThickness = 1;
            this.btnChangePassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangePassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnPressedState.IconLeftImage = null;
            this.btnChangePassword.OnPressedState.IconRightImage = null;
            this.btnChangePassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.btnChangePassword.Size = new System.Drawing.Size(154, 36);
            this.btnChangePassword.TabIndex = 0;
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangePassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangePassword.TextMarginLeft = 0;
            this.btnChangePassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.UseDefaultRadiusAndThickness = true;
            this.btnChangePassword.Click += new System.EventHandler(this.btnChangePassword_Click);
            // 
            // btnChangeUsername
            // 
            this.btnChangeUsername.AllowAnimations = true;
            this.btnChangeUsername.AllowMouseEffects = true;
            this.btnChangeUsername.AllowToggling = false;
            this.btnChangeUsername.AnimationSpeed = 200;
            this.btnChangeUsername.AutoGenerateColors = false;
            this.btnChangeUsername.AutoRoundBorders = false;
            this.btnChangeUsername.AutoSizeLeftIcon = true;
            this.btnChangeUsername.AutoSizeRightIcon = true;
            this.btnChangeUsername.BackColor = System.Drawing.Color.Transparent;
            this.btnChangeUsername.BackColor1 = System.Drawing.Color.White;
            this.btnChangeUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangeUsername.BackgroundImage")));
            this.btnChangeUsername.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeUsername.ButtonText = "Change username";
            this.btnChangeUsername.ButtonTextMarginLeft = 0;
            this.btnChangeUsername.ColorContrastOnClick = 45;
            this.btnChangeUsername.ColorContrastOnHover = 45;
            this.btnChangeUsername.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnChangeUsername.CustomizableEdges = borderEdges4;
            this.btnChangeUsername.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangeUsername.DisabledBorderColor = System.Drawing.Color.White;
            this.btnChangeUsername.DisabledFillColor = System.Drawing.Color.White;
            this.btnChangeUsername.DisabledForecolor = System.Drawing.Color.Black;
            this.btnChangeUsername.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangeUsername.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangeUsername.ForeColor = System.Drawing.Color.Black;
            this.btnChangeUsername.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangeUsername.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeUsername.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeUsername.IconMarginLeft = 11;
            this.btnChangeUsername.IconPadding = 10;
            this.btnChangeUsername.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangeUsername.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangeUsername.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeUsername.IconSize = 25;
            this.btnChangeUsername.IdleBorderColor = System.Drawing.Color.White;
            this.btnChangeUsername.IdleBorderRadius = 10;
            this.btnChangeUsername.IdleBorderThickness = 1;
            this.btnChangeUsername.IdleFillColor = System.Drawing.Color.White;
            this.btnChangeUsername.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_edit_30;
            this.btnChangeUsername.IdleIconRightImage = null;
            this.btnChangeUsername.IndicateFocus = false;
            this.btnChangeUsername.Location = new System.Drawing.Point(3, 45);
            this.btnChangeUsername.Name = "btnChangeUsername";
            this.btnChangeUsername.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnChangeUsername.OnDisabledState.BorderRadius = 10;
            this.btnChangeUsername.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeUsername.OnDisabledState.BorderThickness = 1;
            this.btnChangeUsername.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnChangeUsername.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btnChangeUsername.OnDisabledState.IconLeftImage = null;
            this.btnChangeUsername.OnDisabledState.IconRightImage = null;
            this.btnChangeUsername.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangeUsername.onHoverState.BorderRadius = 10;
            this.btnChangeUsername.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeUsername.onHoverState.BorderThickness = 1;
            this.btnChangeUsername.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangeUsername.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangeUsername.onHoverState.IconLeftImage = null;
            this.btnChangeUsername.onHoverState.IconRightImage = null;
            this.btnChangeUsername.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnChangeUsername.OnIdleState.BorderRadius = 10;
            this.btnChangeUsername.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeUsername.OnIdleState.BorderThickness = 1;
            this.btnChangeUsername.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnChangeUsername.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnChangeUsername.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_edit_30;
            this.btnChangeUsername.OnIdleState.IconRightImage = null;
            this.btnChangeUsername.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangeUsername.OnPressedState.BorderRadius = 10;
            this.btnChangeUsername.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangeUsername.OnPressedState.BorderThickness = 1;
            this.btnChangeUsername.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnChangeUsername.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangeUsername.OnPressedState.IconLeftImage = null;
            this.btnChangeUsername.OnPressedState.IconRightImage = null;
            this.btnChangeUsername.Size = new System.Drawing.Size(154, 36);
            this.btnChangeUsername.TabIndex = 5;
            this.btnChangeUsername.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangeUsername.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangeUsername.TextMarginLeft = 0;
            this.btnChangeUsername.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangeUsername.UseDefaultRadiusAndThickness = true;
            this.btnChangeUsername.Click += new System.EventHandler(this.btnChangeUsername_Click);
            // 
            // btnManagementCenter
            // 
            this.btnManagementCenter.AllowAnimations = true;
            this.btnManagementCenter.AllowMouseEffects = true;
            this.btnManagementCenter.AllowToggling = false;
            this.btnManagementCenter.AnimationSpeed = 200;
            this.btnManagementCenter.AutoGenerateColors = false;
            this.btnManagementCenter.AutoRoundBorders = false;
            this.btnManagementCenter.AutoSizeLeftIcon = true;
            this.btnManagementCenter.AutoSizeRightIcon = true;
            this.btnManagementCenter.BackColor = System.Drawing.Color.Transparent;
            this.btnManagementCenter.BackColor1 = System.Drawing.Color.White;
            this.btnManagementCenter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManagementCenter.BackgroundImage")));
            this.btnManagementCenter.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManagementCenter.ButtonText = "Management Center";
            this.btnManagementCenter.ButtonTextMarginLeft = 0;
            this.btnManagementCenter.ColorContrastOnClick = 45;
            this.btnManagementCenter.ColorContrastOnHover = 45;
            this.btnManagementCenter.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnManagementCenter.CustomizableEdges = borderEdges5;
            this.btnManagementCenter.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManagementCenter.DisabledBorderColor = System.Drawing.Color.White;
            this.btnManagementCenter.DisabledFillColor = System.Drawing.Color.White;
            this.btnManagementCenter.DisabledForecolor = System.Drawing.Color.Black;
            this.btnManagementCenter.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManagementCenter.Font = new System.Drawing.Font("Century Gothic", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnManagementCenter.ForeColor = System.Drawing.Color.Black;
            this.btnManagementCenter.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManagementCenter.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManagementCenter.IconLeftPadding = new System.Windows.Forms.Padding(0);
            this.btnManagementCenter.IconMarginLeft = 11;
            this.btnManagementCenter.IconPadding = 10;
            this.btnManagementCenter.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManagementCenter.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManagementCenter.IconRightPadding = new System.Windows.Forms.Padding(0);
            this.btnManagementCenter.IconSize = 25;
            this.btnManagementCenter.IdleBorderColor = System.Drawing.Color.White;
            this.btnManagementCenter.IdleBorderRadius = 10;
            this.btnManagementCenter.IdleBorderThickness = 1;
            this.btnManagementCenter.IdleFillColor = System.Drawing.Color.White;
            this.btnManagementCenter.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_category_24;
            this.btnManagementCenter.IdleIconRightImage = null;
            this.btnManagementCenter.IndicateFocus = false;
            this.btnManagementCenter.Location = new System.Drawing.Point(3, 3);
            this.btnManagementCenter.Name = "btnManagementCenter";
            this.btnManagementCenter.OnDisabledState.BorderColor = System.Drawing.Color.White;
            this.btnManagementCenter.OnDisabledState.BorderRadius = 10;
            this.btnManagementCenter.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManagementCenter.OnDisabledState.BorderThickness = 1;
            this.btnManagementCenter.OnDisabledState.FillColor = System.Drawing.Color.White;
            this.btnManagementCenter.OnDisabledState.ForeColor = System.Drawing.Color.Black;
            this.btnManagementCenter.OnDisabledState.IconLeftImage = null;
            this.btnManagementCenter.OnDisabledState.IconRightImage = null;
            this.btnManagementCenter.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnManagementCenter.onHoverState.BorderRadius = 10;
            this.btnManagementCenter.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManagementCenter.onHoverState.BorderThickness = 1;
            this.btnManagementCenter.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnManagementCenter.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManagementCenter.onHoverState.IconLeftImage = null;
            this.btnManagementCenter.onHoverState.IconRightImage = null;
            this.btnManagementCenter.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnManagementCenter.OnIdleState.BorderRadius = 10;
            this.btnManagementCenter.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManagementCenter.OnIdleState.BorderThickness = 1;
            this.btnManagementCenter.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnManagementCenter.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnManagementCenter.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_category_24;
            this.btnManagementCenter.OnIdleState.IconRightImage = null;
            this.btnManagementCenter.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnManagementCenter.OnPressedState.BorderRadius = 10;
            this.btnManagementCenter.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManagementCenter.OnPressedState.BorderThickness = 1;
            this.btnManagementCenter.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnManagementCenter.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManagementCenter.OnPressedState.IconLeftImage = null;
            this.btnManagementCenter.OnPressedState.IconRightImage = null;
            this.btnManagementCenter.Size = new System.Drawing.Size(154, 36);
            this.btnManagementCenter.TabIndex = 4;
            this.btnManagementCenter.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManagementCenter.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManagementCenter.TextMarginLeft = 0;
            this.btnManagementCenter.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManagementCenter.UseDefaultRadiusAndThickness = true;
            this.btnManagementCenter.Click += new System.EventHandler(this.btnManagementCenter_Click);
            // 
            // btnMore
            // 
            this.btnMore.AllowAnimations = true;
            this.btnMore.AllowMouseEffects = true;
            this.btnMore.AllowToggling = false;
            this.btnMore.AnimationSpeed = 200;
            this.btnMore.AutoGenerateColors = false;
            this.btnMore.AutoRoundBorders = false;
            this.btnMore.AutoSizeLeftIcon = true;
            this.btnMore.AutoSizeRightIcon = true;
            this.btnMore.BackColor = System.Drawing.Color.Transparent;
            this.btnMore.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnMore.BackgroundImage")));
            this.btnMore.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMore.ButtonText = "";
            this.btnMore.ButtonTextMarginLeft = 0;
            this.btnMore.ColorContrastOnClick = 45;
            this.btnMore.ColorContrastOnHover = 45;
            this.btnMore.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnMore.CustomizableEdges = borderEdges6;
            this.btnMore.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnMore.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMore.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMore.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMore.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnMore.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnMore.ForeColor = System.Drawing.Color.White;
            this.btnMore.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnMore.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnMore.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnMore.IconMarginLeft = 11;
            this.btnMore.IconPadding = 0;
            this.btnMore.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnMore.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnMore.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnMore.IconSize = 25;
            this.btnMore.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.IdleBorderRadius = 1;
            this.btnMore.IdleBorderThickness = 1;
            this.btnMore.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.IdleIconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_more_50__1_;
            this.btnMore.IdleIconRightImage = null;
            this.btnMore.IndicateFocus = false;
            this.btnMore.Location = new System.Drawing.Point(256, 27);
            this.btnMore.Name = "btnMore";
            this.btnMore.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnMore.OnDisabledState.BorderRadius = 1;
            this.btnMore.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMore.OnDisabledState.BorderThickness = 1;
            this.btnMore.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnMore.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnMore.OnDisabledState.IconLeftImage = null;
            this.btnMore.OnDisabledState.IconRightImage = null;
            this.btnMore.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.onHoverState.BorderRadius = 1;
            this.btnMore.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMore.onHoverState.BorderThickness = 1;
            this.btnMore.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnMore.onHoverState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_more_48;
            this.btnMore.onHoverState.IconRightImage = null;
            this.btnMore.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.OnIdleState.BorderRadius = 1;
            this.btnMore.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMore.OnIdleState.BorderThickness = 1;
            this.btnMore.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnMore.OnIdleState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_more_50__1_;
            this.btnMore.OnIdleState.IconRightImage = null;
            this.btnMore.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.OnPressedState.BorderRadius = 1;
            this.btnMore.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnMore.OnPressedState.BorderThickness = 1;
            this.btnMore.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.btnMore.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnMore.OnPressedState.IconLeftImage = global::NguyenTienDat_10122119.Properties.Resources.icons8_more_48;
            this.btnMore.OnPressedState.IconRightImage = null;
            this.btnMore.Size = new System.Drawing.Size(46, 26);
            this.btnMore.TabIndex = 4;
            this.btnMore.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnMore.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnMore.TextMarginLeft = 0;
            this.btnMore.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnMore.UseDefaultRadiusAndThickness = true;
            this.btnMore.Click += new System.EventHandler(this.btnMore_Click);
            // 
            // lblEmail
            // 
            this.lblEmail.AllowParentOverrides = false;
            this.lblEmail.AutoEllipsis = false;
            this.lblEmail.CursorType = null;
            this.lblEmail.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.lblEmail.Location = new System.Drawing.Point(22, 206);
            this.lblEmail.Name = "lblEmail";
            this.lblEmail.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblEmail.Size = new System.Drawing.Size(184, 19);
            this.lblEmail.TabIndex = 4;
            this.lblEmail.Text = "anyone@someone.com";
            this.lblEmail.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblEmail.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblName
            // 
            this.lblName.AllowParentOverrides = false;
            this.lblName.AutoEllipsis = false;
            this.lblName.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblName.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblName.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.lblName.Location = new System.Drawing.Point(22, 163);
            this.lblName.Name = "lblName";
            this.lblName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblName.Size = new System.Drawing.Size(74, 19);
            this.lblName.TabIndex = 3;
            this.lblName.Text = "Someone";
            this.lblName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // frmSuccessfully
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(574, 402);
            this.Controls.Add(this.bunifuPanel1);
            this.ForeColor = System.Drawing.Color.Black;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frmSuccessfully";
            this.Text = "frmSuccessfully";
            this.Load += new System.EventHandler(this.frmSuccessfully_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.imgProfile)).EndInit();
            this.pnlMore.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel lblEmail;
        private Bunifu.UI.WinForms.BunifuLabel lblName;
        private Bunifu.UI.WinForms.BunifuPanel pnlMore;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManagementCenter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangeUsername;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangePassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogOut;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnMore;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEditProfilePicture;
        private Bunifu.UI.WinForms.BunifuPictureBox imgProfile;
    }
}